### ISSUE TITLE
Model user via gem devise - privileges manquant 

### ISSUE THREAD

**Issue by lauravidal-vl** [fabien-git/empnloc#1]
Hello @fabien-git 
J'ai supprimé le modèle User et les clés associées puis j'ai recréé le modèle User via la gem 'devise' mais j'ai le message d'erreur suivant dans le terminal:

_StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "users" does not exist
/home/laura/code/fabien-git/empnloc/db/migrate/20240210054812_create_appointments.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist
/home/laura/code/fabien-git/empnloc/db/migrate/20240210054812_create_appointments.rb:3:in `change'

_Caused by:
PG::UndefinedTable: ERROR:  relation "users" does not exist
/home/laura/code/fabien-git/empnloc/db/migrate/20240210054812_create_appointments.rb:3:in `change'
Tasks: TOP => db:migrate:reset => db:migrate__

En cherchant je suis tombée là-dessus sur stackoverflow: https://stackoverflow.com/questions/50938476/relation-users-does-not-exist-postgresql

A priori cela arrive si l'utilisateur n'a pas les 'schema level privileges'. Est-ce que tu pourrais accorder les droits à tous s'il te plaît ? Je testerai ensuite si cela résout le problème. 

Merci

**Comment by fabien-git** [comment]
tu as déjà tout les droits sur le projet que tu as récupéré.
Sur StackOverflow il parle de droits utilisateur sur la base de données PostGre lors de la création. Normalement, tout ces droits sont gérés lorsque le projet a été généré avec la commande rails new notre_projet -d postgresql.
Sur les messages d'erreur, il est marqué que la table users n'existe pas. 
As-tu bien fait ces commandes après avoir ajouter la gem 'devise'
bundle install
rails generate devise:install

Si oui, alors il faut certainement supprimé la table appointment de telle sorte que lors de la migration users et employees soient crées, puis ensuite appointments .

Autre chose que j'ai pensé, mais cela ne concerne pas ce point.
Pour mieux distribuer les taches entre vous 3.
Une personne peut s'occuper de créer le controller employees  + views associés
Une personne peut s'occuper de appointments  + views asssociés
Une dernière personne s'occupe de générer les seeds.

De notre coté avec Ingrid, en plus du figma, on commencera a faire les vues partielles des views (nav, header, cards) + composants css.

**Comment by lauravidal-vl** [comment]
Oui j'ai fait ces commandes.
Du coup j'ai supprimé la table Appointment cela semble fonctionner. 
Je viens de push ma branche, je te laisse regarde. J'espère que c'est ok j'ai fait une petite erreur sur mon premier commit sur la génération du controller appointment sur lequel j'ai oubli un 's' ...
Merci
